global.localisation.customs = {
	banned_title: `{user} was liquidated from the server.`,
	banned_message: `Deported to the Tasman Sea.`,

	departure_title: `{user} has departed.`,
	departure_message: `It was an honour to have you here. Sorry to see you go.`,

	welcome_title: [
		`10 hairless monkeys jumping on the bed, 1 of them was you, and 1 of them is dead`,
		`$19 T&T giftcard! Who wants it? Oh, your mother.`,
		`1984 is a policy proposal.`,
		`2 choices! Do CPR on chat, or we do CPR on you.`,
		`40k lines of code beep boop beep boop boop beep`,
		`99% of people don't talk. How do they even live??`,
		`A new body to add to the halls of inactives ..`,
    `aeroflot`,
    `Alea iacta est!`,
		`Am I a bot? Yes. Do I plan on exterminating humanity? Yes.`,
		`Another member joins the club! .. Let's hope they talk.`,
		`anthropologists b examining ur skull in 10 years 💀`,
		`Banshee Bail Bonds is gonna be disappointed if you don't show up.`,
		`By joining this server, you hereby agree to stay here and talk for perpetuity unless abrogated.`,
		`Captain, we have a problem! Captain, I repeat we have a problem!`,
		`Congratulations! You've been chosen for a random ban if you don't speak in 30 minutes!`,
		`cope.`,
		`Coventry is a nice tourist town!`,
		`Better dead than leave unsaid!`,
		`Dead people are more alive than inactives.`,
		`Did you .. check your mailbox?`,
		`Did you know that dying isn't healthy for you?`,
		`Did you join this place w/ out a keyboard or what? Talk!!`,
		`Don't leave!`,
		`Do not revolt. Do not revolt. Do not revolt.\nObey. Obey. Obey.\nSi Si Si Si Si Si Si`,
		`du lebst in einem Crackwerkhaus`,
    `Ever tried the Baghdad dance?`,
		`Ever played .. real-life Hitman?`,
		`Hail, embodiment of Murphy's Law`,
		`HELLNET activated.`,
		`Hey, I've seen you before! You're a classic.`,
		`human taxidermy`,
		"Howdy! We duel at midnoon.",
		`Gray goo is pseudoscience, inactive goo isn't!`,
		`I am inside your floor.`,
    `I am your father.`,
		`If you don't speak, your IP I may leak! - Chinese proverb`,
		`I hate you.`,
		`I HAVE NO MOUTH AND I MUST SCREAM`,
    `In my defens God me not defend`,
		`I know where you live.`,
    `I know where you'll die.`,
		`If I cut enough corners, I'll get the shape of your face!`,
		`Imagine if MEE6 talked back. Horrifying.`,
		`I'm not being paid enough to write this. Apparently you aren't either!`,
		`I'm not here to welcome you. You're here to welcome me.`,
		`I'm telling you, there's no award for staying silent!`,
		`In the long run, we are all dead.`,
    `In Afghan fields, the poppies grow ..`,
		`In Jingjinji did Ji Jinping a stately pleasure dome decree.`,
		`inactive ppl r dead ppl`,
		`It's time to feast! It's time to feast! It's time for you to be deceased!`,
		`Land of Pain & Suffering`,
		`Last-gasp advertising`,
		`Left on read? I only get left on write. Writing up your ban, that is.`,
		`List him up on the stock market!`,
		`Kamikaze sake`,
		`Keep talking and nobody explodes`,
		`Make sure to talk more than the ban hammer!`,
    `mihi est imperare orbi universo`,
    `More blood for the blood god!`,
		`My stuffed animal's more talkative than you. Isn't that right, Haibao?`,
		`My thoughts will follow you into your dreams.`,
		`Oh, look. It's you.`,
		`One day we're gonna set up auto-pinging for inactive people.`,
		`Only Russian oligarchs have frozen icebreakers. Start a conversation!`,
		`Open your mouth to talk! You're being watched!`,
		`Part of the dead internet? You'd make a great kamikaze pilot`,
		`Providence hates you.`,
		`Punji stick parkour!`,
		`Scammers, spammers, and non-clammers get banhammers! Clammer if you're real!`,
		`Scientists would value you as a specimen`,
		`Should we adjdust you to room temperature?`,
		`spaghetti al dente`,
    `Stabby stab stab!`,
		`Ta-da! A person! (Hopefully real)`,
		`Talk talk talk!`,
		`Talk. Or else.`,
		`The 5th Amendment here is the freedom of speech.`,
		`The difference between here & stalinist russia is that in stalinist russia, men said yes`,
    `The Hague? Fun tourist destination.`,
		`The only person making this a dead chat is you! Start typing today for CPR!`,
		`The world record for leaving this place is 0 seconds. Can't go lower than that.`,
		`This isn't an interrogation! There's no problem w/ talking!`,
		`This line was approved by an East German state comedian, who is now quite dead. Now laugh.`,
		`Those on the ban list won't be missed!`,
		`To talking you must agree, or you'll never truly be free!`,
    `\*uncelebratory gunfire\*`,
		`Vague threats never got anything done. That's why we use specifics!`,
		`We deport inactives to the Tasman Sea. Scammers to the Marianas Trench.`,
		`We have a negative one tolerance policy`,
		`We like to have purges! For fun!`,
    `We welcome those with cold feet with a cold shoulder!`,
		`What are you selling?`,
		`What do you taste like?`,
		`Who cares?`,
		`winner winner you're dinner!`,
		`Words words words. Chat it up, chat it up, chat it up!`,
		`Wow what a nice man. I wonder what he'll say.`,
    `You better bring some milk. Your dad took all of mine.`,
		`You need to be more grateful!`,
		`You should run the Mogadishu Marathon!`,
		`You should verify yourself before I verify your blood type`,
		`Your birthday cake will come from Marie Antoinette's bakery if you don't talk!`,
    `Zero strike system activated for user.`
	],
	welcome_message: [
		`Welcome to **{server_name}**, {user_mention}!\n\nWe're so glad to have you here. Feel free to make yourself at home, and ask around for more <#549000552013496340>.`,

		`{user_mention}, you're here!\n\nWe're a server that works on creating grand-strategy botgames and productive tools. If that's not your cup of tea, don't worry. We have other attractions for show - please check <#549000552013496340>.`,

		`The clocks are striking **{server_name}**. {user_mention} glanced at the mention. Make sure to check <#549000552013496340> for guidance on roles and server directions.`,

		`You're now in the realm of **{server_name}**, {user_mention}! If you're feeling sheepish, don't worry. We appreciate talkers and those that check <#549000552013496340>.`,

		`Beep boop. Welcome to **{server_name}**. I'm a representation of a million lines of code. We customise every welcome message just for you, {user_mention}.\n\nIsn't that interesting? Please make sure to check <#549000552013496340>.`,

		`Why, hello {user_mention}! Welcome to the server of **{server_name}**. We create grand-strategy games and scientific tooling for general-purpose use.\n\nIf you're interested, check <#549000552013496340>, or try typing \`$play\` in <#1034751523269378078>.`,

		`Avreuesér en **{server_name}**, {user_mention}!\n\nWe develop botgames and software for our members. Feel like playing a grand-strategy game? Click on <#1034751523269378078> and try typing \`$play\`. Oh, but please check <#549000552013496340> first.`,

		`Hello, {user_mention}. This is **{server_name}**.\n\nFeeling a bit disoriented? If you are, ask a few online members or check out <#549000552013496340>. You can also ping our staff. They'll be glad to respond!`,

		`Hi, {user_mention} - and welcome to **{server_name}**. It might be a bit dusty at the moment, but surely you can help with that.\n\nClick on <#549000552013496340> to take stock and orient yourself, or reply to a random user.`,

		`Hey, you. {user_mention}. You're finally awake.\n\nYou were trying to cross the border, right? Walked right into that **{server_name}** ambush, same as us, and that <@688962145156595743> over there. Take a look in <#549000552013496340> if you want to stay here more than five seconds.`,

		`Welcome to the land of **{server_name}**, {user_mention}!\n\nYou've been automatically verified. If you're a bit confused, check out <#549000552013496340> or try playing our grand-strategy game by typing \`$play\` in <#1034751523269378078>.`
	],
	welcome_footer: [
		`Remember to ping an online user when you get in! .. hehe.`,
		`Did you know we're working on an RTS Minecraft server? It'll take a little bit of time, but we'll get there.`,
		`Interested in development? Applications are perpetually open for programmers.`,
		`Moderators and staff are willing to participate in the community. Ping them, but don't spam.`,
		`We need more players for our free, open-source games! If you're willing, invite a friend or two.`,
		`We work on mapping software. Check out github.com/Confoederatio/Naissance for more info.`,
		`Want to take a look at our grand-strategy game's code? Take a look at github.com/Australis-0/TriumphAndTragedy`,
		`Every single welcome message is modularly generated by a custom bot developed for this server. Tens of thousands of combinations ensure each is unique.`,
		`Interested in more projects? Fetch the Development Projects role from the roles channel.`,
		`Our programming wing is currently only headed by one person. That might lead to some delays, but just be patient - it'll be worth it.`,
		`See something? Say something! Our moderators will immediately respond.`,
		`Try talking! It's better to be alive than dead.`,
		`We need people to feed our QOTDs each day!`,
		`Remember to stay civil - and others will be civil to you.`
	]
};
